---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  ansible.builtin.copy:
    src: "roles/deploy/files/artifact.tar.gz"
    dest: "~/web/artifact.tar.gz"

- name: Executing node
  shell: |
    tar -xvf ~/web/artifact.tar.gz -C ~/web/
    cd ~/web/dist
    npm install
    pm2 stop default
    pm2 start main.js
