---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "files/artifact.tar.gz"
    dest: "~/web/artifact.tar.gz"

- name: Executing node
  shell: |
    tar -xvf ~/web/artifact.tar.gz -C ~/web/
    cd ~/web/dist
    npm install
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"
